drop table movies;

CREATE EXTERNAL TABLE movies (
      movie_id INT,
      title STRING,
      genres ARRAY<STRING>)
  ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ':'
  COLLECTION ITEMS TERMINATED BY '|'
  LINES TERMINATED BY '\n'
  STORED AS TEXTFILE
  LOCATION "/data/movies_v1/movies";

SHOW TABLES;
