#!/bin/ksh

echo 'Running linuxgenericprof.'
set -o vi
# set default access to read write execute for all newly created directories.
umask 000

# Set some user related variables
export NETHOME=/home

export BUILD_ROOT=/net/nar200/vol/vol2/pre_rel/essbase/builds
export SXR_HOME=/home/essbasesxr/talleyrand/vobs/essexer/latest


export ESSLANG=English_UnitedStates.Latin1@Binary
#export SXR_MLCAPP=1
#export ESSCMDQ_UTF8MODE=1
stty erase ^H
stty intr ^C
stty erase ^?
export PATH=\
/bin:\
/usr/bin:\
/usr/sbin:\
/usr/X11R6/bin:\
/etc:\
/usr/local/bin:\
/usr/ucb:\
/usr/atria/bin:\
${ARBORPATH}/bin:\
${ARBORPATH}/dlls:\
${NFSHOME}/bin:\
${SXR_HOME}/bin:\
${BUILD_ROOT}/common/bin:\
${JRE_HOME}/bin

#HOSTNAME=`/usr/bin/uname -n`
#TTY=`tty | tr "/" "-"`

# Don't export PS1 under SunOS, because if a Bourne shell is subsequently
# spawned, then the prompt will be literally be "${LOGNAME}@${HO ..." rather
# than the expansion of those variables.
#


export PS1="
\$PWD
($LOGNAME@`uname -n`)\>"

export TERM=vt100
#resize

export HISTFILE=${HOME}/history/.${HOSTNAME}${TTY}.sh_history

alias myterm='/usr/X11R6/bin/xterm -bg black -fg green -fn 8x13 -sb -sl 1200 -title "stnti8" &'

# Increase shell max limits
# Set max number of file descriptors to 1024
ulimit -n 4096

# For Linux specificily:
ulimit -s  unlimited

stty erase ^H
stty intr ^C
stty erase ^?

ESSLANG=English_UnitedStates.Latin1@Binary

export PATH="$JRE_HOME/bin:$PATH"
alias view='cd $ARBORPATH/../views'
alias ..='cd ..'
alias ...='cd ../../../'
alias h=history

alias cfg='cat $ARBORPATH/bin/essbase.cfg'

# For autopilot test

export PATH=".:$HOME/autoregress:$HOME/bin:$PATH"

export http_proxy=http://www-proxy.us.oracle.com
alias home='cd /home'

cd /home

mount -t cifs -o username=qa,password=Systest1 //nar200/hit /mnt/hit

export AP_NOPLAT=false
export PROD_ROOT=/home/$LOGNAME/hyperion
export AP_KEEPWORK=1
alias essbase='cd /mnt/TachyonRaid/diskarray/home/$LOGNAME/hyperion'
#export AP_CLEANUPVIEWFOLDERS=false
export SXR_STA_ACCUMULATED=1

export AP_LOGTO=/home/$LOGNAME/$LOGNAME@tachyon.log

export AP_HITCACHE=/mnt/TachyonRaid/diskarray/hitcache
